name: Code Style
on: [push]

jobs:
  lint:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node: [12, 14, 16]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installing
        run: npm ci
      - name: Linting
        run: npm run lint

  format:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12, 14, 16]
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installing
        run: npm ci
      - name: Linting
        run: npm run format:check
